### ISSUE TITLE
Cannot destructure imports

### ISSUE THREAD

**Issue by th3fallen** [maccuaa/formsy-react-2#3]
Am i missing something or is the ability to do . `import {Mixin} from 'formsy-react-2'` missing?

**Comment by th3fallen** [comment]
nevermind i forgot to remove HOC(ComponentName)

**Comment by th3fallen** [comment]
Nevermind i still get Mixin is not defined

**Comment by maccuaa** [comment]
The way the project is structured right now no you can't import like that.  Mixin is added as a property to the the Formsy object that's exported from main.js which is why you have to do 

```jsx
import Formsy from 'formsy-react-2'

class myClass extends Formsy.Mixin
```

Alternatively you could try `import Mixin from 'formsy-react-2/lib/Mixin';`.

I realize this is not ideal and a restructuring of the project is definitely needed.
